export type CPDBType = {
	sorting_number: String
	municipality: String
	barangay: String
	zone: String
	household_number: String
	household_characteristics: String
	number_of_persons_living: String
	household_size_bracket: String
	number_of_families: String
	line_number_of_household_member: String
	name_of_household_member: String
	relationship_to_household_head: String
	sex: String
	date_of_birth: String
	age: String
	age_bracket: String
	civil_status: String
	highest_educational_attainment: String
	school_attendance: String
	level_of_school_attendance: String
	reason_for_not_attending_school: String
	religious_affiliation: String
	have_special_skills: String
	type_of_special_skill: String
	presence_of_disability: String
	type_of_disability: String
	indigenous_group_or_tribe: String
	name_of_group_or_tribe: String
	active_philhealth_member: String
	philhealth_membership_specify: String
	usual_occupation_of_working_household_member: String
	gross_monthly_income: String
	income_bracket: String
	place_of_work: String
	number_of_years_stay: String
	number_of_years_bracket: String
	fp_currently_used: String
	total_household_monthly_income: String
	household_income_bracket: String
	house_ownership: String
	house_levels: String
	house_construction_material: String
	homelot_ownership_or_tenure_status: String
	source_of_drinking_water: String
	type_of_toilet: String
	garbage_disposal: String
	type_of_lighting_fuel: String
	type_of_cooking_fuel: String
	geohazard_area: String
	household_location: String
	flood_prone_area_water_level: String
	access_to_infotech: String
	'4ps_beneficiary_household': String
}
