export const ByAgeGroupConfig = {
	options: {
		scaleShowVerticalLines: false,
		responsive: true,
	},
	labels: ['15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45 & Up'],
	legend: true,
	colors: [],
	datasets: [
		{
			data: [
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
			],
			label: 'Females',
		},
		{
			data: [
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
			],
			label: 'Males',
		},
		{
			data: [
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
			],
			label: 'Total',
		},
	],
}
