export const ByCIvilStatusConfig = {
	options: {
		scaleShowVerticalLines: false,
		responsive: true,
	},
	labels: ['Single', 'Co-Habiting/Live-in', 'Widow/er', 'Devorced/Separated'],
	legend: true,
	colors: [],
	datasets: [
		{
			data: [
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
			],
			label: 'Females',
		},
		{
			data: [
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
			],
			label: 'Males',
		},
		{
			data: [
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
				Math.random(),
			],
			label: 'Total',
		},
	],
}
