export const DummyData = [
	['Age', 'Female', 'Male'],
	['Below 1 Year Old', -Math.random(), Math.random()],
	['5-9', -Math.random(), Math.random()],
	['10-14', -Math.random(), Math.random()],
	['15-19', -Math.random(), Math.random()],
	['20-24', -Math.random(), Math.random()],
	['25-29', -Math.random(), Math.random()],
	['30-34', -Math.random(), Math.random()],
	['35-39', -Math.random(), Math.random()],
	['40-44', -Math.random(), Math.random()],
	['45-49', -Math.random(), Math.random()],
	['50-54', -Math.random(), Math.random()],
	['55-59', -Math.random(), Math.random()],
	['60-64', -Math.random(), Math.random()],
	['65-69', -Math.random(), Math.random()],
	['70-74', -Math.random(), Math.random()],
	['75-79', -Math.random(), Math.random()],
	['80 and Above', -Math.random(), Math.random()],
]
