export const PopProfileDummy = {
	'Total No. of Barangays': 'N/A',
	'Total Land Area': 'N/A',
	'Total Household Population': 'N/A',
	Males: 'N/A',
	Females: 'N/A',
	'Sex Ratio': 'N/A',
	'Median Age': 'N/A',
	'Doubling Time/Year': 'N/A',
	'Population Growth Rate': 'N/A',
	'No. of Households': 'N/A',
	'Average Household Size': 'N/A',
	'Population Density': 'N/A',
	'Age Dependency Ratio': 'N/A',
	'Child Dependency Ratio': 'N/A',
	'Old-Age Dependency Ratio': 'N/A',
}
