import {PreMarriageData} from '../../models/PMOC.model'

export const preMarriageData: PreMarriageData = {
    males: {
        January: 0,
        February: 0,
        March: 0,
        April: 0,
        May: 0,
        June: 0,
        July: 0,
        August: 0,
        September: 0,
        October: 0,
        November: 0,
        December: 0,
    },
    females: {
        January: 0,
        February: 0,
        March: 0,
        April: 0,
        May: 0,
        June: 0,
        July: 0,
        August: 0,
        September: 0,
        October: 0,
        November: 0,
        December: 0,
    },
    type: 'PMOC',
    year: new Date(Date.now()).getFullYear(),
    municipality: null,
    barangay: null,
    months: undefined,
}
